---
- name: Install logrotate
  package:
    name: logrotate
    state: present

- name: Configure logrotate
  template:
    src: templates/logrotate.conf.j2
    dest: /etc/logrotate.conf

- name: Configure logrotate.d file for role
  template:
    src: templates/logrotate.d.j2
    dest: /etc/logrotate.d/{{ item.name }}
  with_items: "{{ logrotate_applications }}"
  tags:
    - as_dependency
